module examples.vqe;

import std.complex;

import quantum.pure_state.qc;
import quantum.pure_state.observable;

import vqe.vqe;

/*
* The Variational Quantum Eigensolver is a variational quantum algorithm which minimizes the energy of a system
* given by a specific hamiltonian decomposed into a series of pauli operator strings with coefficients. The algorithm
* being variational means that it modifies some trainable parameters theta in order to minimize the energy of the system. 
* The expectation value of the hamiltonian gives an energy for a specific state and the classical optimizer modifies 
* the trainable parameters in order to minimize the energy given by the expectation value of the hamiltonian.
*/

// Example 1:

/* 
* The variational quantum circuit uses trainable parameters
* to rotate qubits about an axis or various axes in order to later calculate the 
* energy given by that state. The hamiltonian acts as a cost function which 
* calculates the expectation value of the energy in order to update the trainable parameters 
* using a classical optimizer function. This in turn minimizes the energy of the system.
* The circuit may also in some cases have to entangle qubits in order to adhere to the 
* structure and requirements of the terms given by the hamiltonian decomposition.
*/
QuantumCircuit vqc(QuantumCircuit qc, real[] trainable_params) {
    // Rotate the qubits about the Y-axis because the hamiltonian
    // does not contain pauli-Y terms which means that the axis of rotation
    // anti-commutes with the terms in the hamiltonian decomposiiton.
    qc.ry(0, trainable_params[0]);
    qc.ry(1, trainable_params[1]);
    qc.ry(2, trainable_params[2]);

    // Entanglement chain which follows the structure of the hamiltonian.
    // This is mainly done because of the competition between classical states of 
    // spin alignment and quantum fluctuations generated by the neccessity for superposition
    // in the X basis
    qc.cnot(0, 1);
    qc.cnot(1, 2);
    qc.cnot(2, 0);

    // Rotate the qubits about the Y-axis again with different trainable parameters
    // in order to make the ansatz more expressive
    qc.ry(0, trainable_params[3]);
    qc.ry(1, trainable_params[4]);
    qc.ry(2, trainable_params[5]);

    // Undo the entanglement, not doing this leads to a wrong answer
    qc.cnot(0, 1);
    qc.cnot(1, 2);
    qc.cnot(2, 0);

    return qc;
}

void main() {
    // Define the observable or hamiltonian for the system whose energy we are trying to minimize.
    // In this case we define the transverse field ising model hamiltonian and calculate its minimum energy
    // eigenstate.
    Observable hamiltonian = Observable([
        "ZZI", "IZZ", "ZIZ", "XII", "IXI", "IIX"
    ], [
        Complex!real(-1, 0), Complex!real(-1, 0), Complex!real(-1, 0),
        Complex!real(-0.7, 0), Complex!real(-0.7, 0), Complex!real(-0.7, 0)
    ], 3);

    // Initialize the VQE algorithm with 3 qubits, the previously defined hamiltonian. 6
    // trainable parameters to make the ansatz more expressive, 180 total iterations of the 
    // algorithm, a learning rate which is reasonable (not too high or low) and the ansatz which 
    // we previously defined.
    int num_qubits = 3;
    real[] trainable_params = [-0.13, 0.23, -0.15, 0.2, 0.11, -0.06];
    real learning_rate = 0.16;
    int iterations = 180;
    VQE vqe = VQE(num_qubits, hamiltonian, trainable_params, iterations, learning_rate, &vqc);

    // Execute the algorithm, the minimum energy should converge to -3.477
    vqe.vqe();
}
